//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitBootStrap.Data
{

    using GitBootStrap.Domain.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
            Database.SetInitializer<Model1Container>(new Model1ContainerInitializer());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Player> Players { get; set; }

        class Model1ContainerInitializer : DropCreateDatabaseAlways<Model1Container>
        {
            protected override void Seed(Model1Container myContext)
            {
                Team t = new Team();
                t.Name = "Cameroon";
                myContext.Teams.Add(t);
                myContext.SaveChanges();
            }
        }

        public virtual void Commit()
        {
            base.SaveChanges();
        } 
    }
}
